// <auto-generated />
using Haverim.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Haverim.Migrations
{
    [DbContext(typeof(HaverimContext))]
    partial class HaverimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Haverim.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PostId");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("Haverim.Models.Comment", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Body");

                    b.Property<Guid?>("PostId");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("PublisherId");

                    b.Property<string>("_upvoteUsers");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Haverim.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PostId");

                    b.Property<DateTime>("PublishDate");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Haverim.Models.Post", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Body");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("PublisherId");

                    b.Property<string>("_upvoteUsers");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Haverim.Models.User", b =>
                {
                    b.Property<string>("Username");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Country");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email");

                    b.Property<bool>("IsMale");

                    b.Property<DateTime>("JoinDate");

                    b.Property<string>("Password");

                    b.Property<string>("ProfilePic");

                    b.Property<string>("_followers");

                    b.Property<string>("_following");

                    b.Property<string>("_postFeed");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Haverim.Models.Activity", b =>
                {
                    b.HasOne("Haverim.Models.User")
                        .WithMany("ActivityFeed")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("Haverim.Models.Comment", b =>
                {
                    b.HasOne("Haverim.Models.Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Haverim.Models.Notification", b =>
                {
                    b.HasOne("Haverim.Models.User")
                        .WithMany("Notifications")
                        .HasForeignKey("Username");
                });
#pragma warning restore 612, 618
        }
    }
}
